title: "République française"
description: "Official website of the French Republic (roleplay)"
baseurl: "" # Leave blank for root
url: "https://<your-username>.github.io/french-republic-site"
language: en

# Theme
theme: jekyll-theme-minimal

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Departments"
    url: "/departments/"
  - title: "President"
    url: "/president/"
  - title: "Prime Minister"
    url: "/prime-minister/"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge
