title: République française
description: Empowered by the Constitution and the French people.

# Theme and plugins
theme: minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Departments"
    url: "/departments/"
  - title: "President"
    url: "/president/"
  - title: "Prime Minister"
    url: "/prime-minister/"

# Footer details
footer:
  text: "© 2024 République française. All rights reserved."

# Additional site settings
baseurl: "" # Leave blank for root deployment
url: "https://<your-username>.github.io/french-republic-site"
language: en
markdown: kramdown
highlighter: rouge
